urls.py
from bonvortaro.vortaro import models
from bonvortaro.vortaro import views
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.list_detail import object_list, object_detail

admin.autodiscover()

roots = {
    "queryset": models.Root.objects.order_by("root"),
    "template_object_name": "root"
}
words = {
    "queryset": models.Word.objects.order_by("word"),
    "template_object_name": "word"
}

urlpatterns = patterns(
    '',
    
    url(r"^root/$", object_list, roots, name="roots"),
    url(r"^root/(?P<object_id>\d+)/$", object_detail, roots, name="root"),
    url(r"^word/$", object_list, words, name="words"),
    url(r"^word/(?P<object_id>\d+)/$", object_detail, words, name="word"),
    url(r"^search/$", views.search, name="search"),
    
    url(r'^admin/(.*)', admin.site.root, name="admin"),
)

vortaro/models.py
# -*- coding: utf-8 -*-
# Copyright (C) 2008  José Pablo Fernández Silva
#
# This file is part of Bonvrtaro.
#
# Bonvortaro is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Bonvortaro is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with Bonvortaro.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models

#WORD_TYPES = (
#    ("s", "suffix"),
#    ("p", "prefix"),
#    ("n", "noun"),
#    ("nn", "plural noun"),
#    ("a", "adjective"),
#    ("aa", "plural adjective"),
#    ("v", "verb"),
#    ("d", "adverb")
#)

def _to_xsistemo(s):
    """Turn a nice unicode string into an hideous x-sistemo one."""
    replacements = [
        (u"Ĉ", "Cx"),
        (u"ĉ", "cx"),
        (u"Ĝ", "Gx"),
        (u"ĝ", "gx"),
        (u"Ĥ", "Hx"),
        (u"ĥ", "hx"),
        (u"Ĵ", "Jx"),
        (u"ĵ", "jx"),
        (u"Ŝ", "Sx"),
        (u"ŝ", "sx"),
        (u"Ŭ", "Ux"),
        (u"ŭ", "ux"),
    ]
    
    for old, new in replacements:
        s = s.replace(old, new)
    
    try:
        s = s.encode("ascii")
        return s
    except:
        return repr(s)

class Root(models.Model):
    root = models.CharField(max_length=70)
    kind = models.CharField(max_length=70, blank=True) #, choices=WORD_TYPES)
    
    # Not used, unknown or Retavortaro specific.
    begining = models.CharField(max_length=70, blank=True)
    ending = models.CharField(max_length=70, blank=True)
    ofc = models.CharField(max_length=70, blank=True)
    #fnt = models.CharField(max_length=20)
    mrk = models.CharField(max_length=100, blank=True)

    def __unicode__(self):
        return self.root

class Word(models.Model):
    language = models.CharField(max_length=3)
    root = models.ForeignKey(Root, blank=True, null=True)
    word = models.CharField(max_length=70)
    kind = models.CharField(max_length=70, blank=True) #, choices=WORD_TYPES)
    
    # Not used, unknown or Retavortaro specific.
    begining = models.CharField(max_length=70, blank=True)
    ending = models.CharField(max_length=70, blank=True)
    ofc = models.CharField(max_length=70, blank=True)
    #fnt = models.CharField(max_length=20)
    mrk = models.CharField(max_length=100, blank=True)

    def __unicode__(self):
        return self.word

    def revo_url(self):
        """Returns the URL for this word in Reta Vortaro."""
        return "http://reta-vortaro.de/revo/art/%s.html#%s" % (_to_xsistemo(self.root.root), self.mrk)

class Definition(models.Model):
    word = models.ForeignKey(Word)
    definition = models.TextField()

    def __unicode__(self):
        return self.definition

vortaro/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)

vortaro/views.py
from django.shortcuts import render_to_response
from bonvortaro.vortaro import forms

def search(request):
    if request.method == 'POST':
        form = forms.SearchForm(request.POST)
    else:
        form = forms.SearchForm(request.GET)
    return render_to_response("vortaro/search.html", {
        "form": form
    })

templates/base.html
{% comment %}
Copyright (C) 2008  José Pablo Fernández Silva

This file is part of Bonvrtaro.

Bonvortaro is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

Bonvortaro is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License along
with Bonvortaro.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <link rel="stylesheet" href="style.css" />
  <title>Bonvortaro: {% block title %}{% endblock %}</title>
</head>
<body>
  <div id="sidebar">
    {% block sidebar %}
    <ol class="menu">
      <li><a href="/">Home</a></li>
      <li><a href="{% url search %}">Search</a></li>
      <li><a href="{% url roots %}">Root words</a></li>
      <li><a href="{% url words %}">Words</a></li>
    </ol>
    {% endblock %}
    {% if user.is_authenticated %}
    <p>Welcome back, {{ user.username }}!</p>
    {% endif %}
  </div>
  <div id="content">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

templates/vortaro/root_detail.html
{% extends "base.html" %}

{% comment %}
Copyright (C) 2008  José Pablo Fernández Silva

This file is part of Bonvrtaro.

Bonvortaro is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

Bonvortaro is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License along
with Bonvortaro.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}Root word: {{ root }}{% endblock %}

{% block content %}
<h1>Root word: {{ root }}</h1>
<dl>
  <dt>Root</dt>
  <dd>{{ root.root }}</dd>
  <dt>Kind</dt>
  <dd>{{ root.kind }}</dd>
</dl>
<h2>Words based on {{ root }}</h2>
<ol class="wordlist">
  {% for word in root.word_set.all %}
  <li><a href="{% url word word.id %}">{{ word }}</a></li>
  {% endfor %}
</ol>
<h2>Unused, unknown or Retavortaro specific information.</h2>
<dl>
  <dt>Begining</dt>
  <dd>{{ root.begining }}</dd>
  <dt>Ending</dt>
  <dd>{{ root.ending }}</dd>
  <dt>Ofc</dt>
  <dd>{{ root.ofc }}</dd>
  <dt>Mrk</dt>
  <dd>{{ root.mrk }}</dd>
</dl>
{% endblock %}

templates/vortaro/root_list.html
{% extends "base.html" %}

{% comment %}
Copyright (C) 2008  José Pablo Fernández Silva

This file is part of Bonvrtaro.

Bonvortaro is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

Bonvortaro is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License along
with Bonvortaro.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}Root words{% endblock %}

{% block content %}
<h1>Root words</h1>
<ol class="wordlist">
  {% for root in root_list %}
  <li><a href="{% url root root.id %}">{{ root }}</a></li>
  {% endfor %}
</ol>
{% endblock %}

templates/vortaro/search.html
{% extends "base.html" %}

{% comment %}
Copyright (C) 2008  José Pablo Fernández Silva

This file is part of Bonvrtaro.

Bonvortaro is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

Bonvortaro is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License along
with Bonvortaro.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}Search{% endblock %}

{% block content %}
<h1>Search</h1>
<form action="{% url search %}" method="GET">
  <p>Search: {{ form.query }} <input type="submit" value="Search"/></p>
</form>
{% comment %}
<ol class="wordlist">
  {% for root in root_list %}
  <li><a href="{% url root root.id %}">{{ root }}</a></li>
  {% endfor %}
</ol>
{% endcomment %}
{% endblock %}

templates/vortaro/word_detail.html
{% extends "base.html" %}

{% comment %}
Copyright (C) 2008  José Pablo Fernández Silva

This file is part of Bonvrtaro.

Bonvortaro is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

Bonvortaro is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License along
with Bonvortaro.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}Word: {{ word }}{% endblock %}

{% block content %}
<h1>Word: {{ word }}</h1>
<dl>
  <dt>Word</dt>
  <dd>{{ word.word }}</dd>
  <dt>Root</dt>
  <dd><a href="{% url root word.root.id %}">{{ word.root }}</a></dd>
  <dt>Kind</dt>
  <dd>{{ word.kind }}</dd>
</dl>
<p>Read about <a href="{{ word.link_to_retavortaro }}">{{ word }} at Retavortaro</a>.</p>
<h2>Unused, unknown or Retavortaro specific information.</h2>
<dl>
  <dt>Begining</dt>
  <dd>{{ word.begining }}</dd>
  <dt>Ending</dt>
  <dd>{{ word.ending }}</dd>
  <dt>Ofc</dt>
  <dd>{{ word.ofc }}</dd>
  <dt>Mrk</dt>
  <dd>{{ word.mrk }}</dd>
</dl>
{% endblock %}

templates/vortaro/word_list.html
{% extends "base.html" %}

{% comment %}
Copyright (C) 2008  José Pablo Fernández Silva

This file is part of Bonvrtaro.

Bonvortaro is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

Bonvortaro is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License along
with Bonvortaro.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}Words{% endblock %}

{% block content %}
<h1>Words</h1>
<ol class="wordlist">
  {% for word in word_list %}
  <li><a href="{% url word word.id %}">{{ word }}</a></li>
  {% endfor %}
</ol>
{% endblock %}